-- ============================================================
-- TÍTULO: Controle Simples de Estoque de Produtos
-- DESCRIÇÃO: Atividade SQL para cadastrar produtos em estoque,
-- controlar quantidade disponível e formatar preços em consultas.
-- BANCO: Supabase / PostgreSQL
-- ============================================================

DROP TABLE IF EXISTS estoque_produtos;

CREATE TABLE estoque_produtos (
    id_produto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL CHECK (LENGTH(TRIM(nome)) > 0),
    quantidade INTEGER NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
    preco NUMERIC(10,2) NOT NULL CHECK (preco >= 0)
);

INSERT INTO estoque_produtos (nome, quantidade, preco)
VALUES
('Caderno', 50, 12.90),
('Caneta azul', 120, 2.50),
('Mochila escolar', 15, 89.90),
('Borracha', 80, 1.50),
('Lápis', 100, 1.20);

-- Consulta: produtos do estoque com preço formatado.
SELECT
    id_produto,
    nome,
    quantidade,
    'R$ ' || REPLACE(TO_CHAR(preco, 'FM999999990.00'), '.', ',') AS preco_formatado
FROM estoque_produtos;
