-- ============================================================
-- TÍTULO: Sistema de Pedidos com Clientes, Produtos e Itens
-- DESCRIÇÃO: Atividade SQL para cadastrar clientes, produtos,
-- pedidos e itens de pedido, usando chaves primárias, estrangeiras,
-- validações CHECK e consultas com JOIN.
-- BANCO: Supabase / PostgreSQL
-- ============================================================

DROP TABLE IF EXISTS itens_pedido;
DROP TABLE IF EXISTS pedidos;
DROP TABLE IF EXISTS produtos;
DROP TABLE IF EXISTS clientes;

CREATE TABLE clientes (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(11),
    email VARCHAR(100),
    cidade VARCHAR(100),
    estado CHAR(2),

    CHECK (cpf ~ '^[0-9]{11}$'),
    CHECK (telefone IS NULL OR telefone ~ '^[0-9]{11}$'),
    CHECK (estado IS NULL OR estado ~ '^[A-Z]{2}$'),
    CHECK (email IS NULL OR email LIKE '%@%')
);

CREATE TABLE produtos (
    id_produto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto VARCHAR(100) NOT NULL,
    categoria VARCHAR(50),
    preco_unitario NUMERIC(10,2) NOT NULL CHECK (preco_unitario >= 0),
    quantidade_disponivel INTEGER NOT NULL CHECK (quantidade_disponivel >= 0)
);

CREATE TABLE pedidos (
    id_pedido BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    data_pedido DATE NOT NULL,
    status_pedido VARCHAR(20) NOT NULL CHECK (
        status_pedido IN ('Aberto', 'Finalizado', 'Cancelado')
    ),

    FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
);

CREATE TABLE itens_pedido (
    id_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido BIGINT NOT NULL,
    id_produto BIGINT NOT NULL,
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),

    FOREIGN KEY (id_pedido) REFERENCES pedidos(id_pedido),
    FOREIGN KEY (id_produto) REFERENCES produtos(id_produto)
);

INSERT INTO clientes (cpf, nome, telefone, email, cidade, estado)
VALUES
('12345678900', 'João', '41999991111', 'joao@email.com', 'Curitiba', 'PR'),
('98765432100', 'Maria', '41988882222', 'maria@email.com', 'Londrina', 'PR');

INSERT INTO produtos (produto, categoria, preco_unitario, quantidade_disponivel)
VALUES
('Milho', 'Grãos', 25.00, 200),
('Soja', 'Grãos', 40.00, 150);

INSERT INTO pedidos (id_cliente, data_pedido, status_pedido)
VALUES
(1, '2026-06-01', 'Finalizado'),
(1, '2026-06-02', 'Finalizado'),
(2, '2026-06-03', 'Aberto');

INSERT INTO itens_pedido (id_pedido, id_produto, quantidade)
VALUES
(1, 1, 10),
(2, 2, 5),
(3, 1, 8);

-- Consulta 1: clientes com CPF e telefone formatados.
SELECT
    id_cliente,
    SUBSTR(cpf, 1, 3) || '.' ||
    SUBSTR(cpf, 4, 3) || '.' ||
    SUBSTR(cpf, 7, 3) || '-' ||
    SUBSTR(cpf, 10, 2) AS cpf_formatado,
    nome,
    '(' || SUBSTR(telefone, 1, 2) || ') ' ||
    SUBSTR(telefone, 3, 5) || '-' ||
    SUBSTR(telefone, 8, 4) AS telefone_formatado,
    email,
    cidade,
    estado
FROM clientes;

-- Consulta 2: produtos com preço formatado.
SELECT
    id_produto,
    produto,
    categoria,
    'R$ ' || REPLACE(TO_CHAR(preco_unitario, 'FM999999990.00'), '.', ',') AS preco,
    quantidade_disponivel
FROM produtos;

-- Consulta 3: pedidos com data formatada.
SELECT
    id_pedido,
    id_cliente,
    TO_CHAR(data_pedido, 'DD/MM/YYYY') AS data_pedido,
    status_pedido
FROM pedidos;

-- Consulta 4: relatório completo dos pedidos.
SELECT
    pedidos.id_pedido AS pedido,
    TO_CHAR(pedidos.data_pedido, 'DD/MM/YYYY') AS data_pedido,
    SUBSTR(clientes.cpf, 1, 3) || '.' ||
    SUBSTR(clientes.cpf, 4, 3) || '.' ||
    SUBSTR(clientes.cpf, 7, 3) || '-' ||
    SUBSTR(clientes.cpf, 10, 2) AS cpf,
    clientes.nome AS cliente,
    '(' || SUBSTR(clientes.telefone, 1, 2) || ') ' ||
    SUBSTR(clientes.telefone, 3, 5) || '-' ||
    SUBSTR(clientes.telefone, 8, 4) AS telefone,
    clientes.cidade,
    clientes.estado,
    produtos.produto,
    produtos.categoria,
    itens_pedido.quantidade,
    'R$ ' || REPLACE(TO_CHAR(produtos.preco_unitario, 'FM999999990.00'), '.', ',') AS preco_unitario,
    'R$ ' || REPLACE(
        TO_CHAR(itens_pedido.quantidade * produtos.preco_unitario, 'FM999999990.00'),
        '.',
        ','
    ) AS valor_total,
    pedidos.status_pedido
FROM itens_pedido
INNER JOIN pedidos
    ON itens_pedido.id_pedido = pedidos.id_pedido
INNER JOIN clientes
    ON pedidos.id_cliente = clientes.id_cliente
INNER JOIN produtos
    ON itens_pedido.id_produto = produtos.id_produto;
