-- ============================================================
-- TÍTULO: Sistema de Locação de Veículos
-- DESCRIÇÃO: Atividade SQL para controlar clientes, veículos e
-- locações, usando chaves primárias, estrangeiras, validações CHECK
-- e consultas com JOIN.
-- BANCO: Supabase / PostgreSQL
-- ============================================================

DROP TABLE IF EXISTS locacoes;
DROP TABLE IF EXISTS veiculos;
DROP TABLE IF EXISTS clientes;

CREATE TABLE clientes (
    cpf VARCHAR(11) PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(11),
    email VARCHAR(100),

    CHECK (cpf ~ '^[0-9]{11}$'),
    CHECK (telefone IS NULL OR telefone ~ '^[0-9]{10,11}$'),
    CHECK (email IS NULL OR email LIKE '%@%')
);

CREATE TABLE veiculos (
    id_veiculo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR(50) NOT NULL,
    modelo VARCHAR(50) NOT NULL,
    ano INTEGER NOT NULL CHECK (ano >= 1900),
    placa VARCHAR(10) NOT NULL UNIQUE,
    valor_diaria NUMERIC(10,2) NOT NULL CHECK (valor_diaria >= 0),
    status_veiculo VARCHAR(20) NOT NULL CHECK (
        status_veiculo IN ('Disponível', 'Locado', 'Manutenção')
    ),

    CHECK (placa ~ '^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$')
);

CREATE TABLE locacoes (
    id_locacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf_cliente VARCHAR(11) NOT NULL,
    id_veiculo BIGINT NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    valor_total NUMERIC(10,2) NOT NULL CHECK (valor_total >= 0),
    status_locacao VARCHAR(20) NOT NULL CHECK (
        status_locacao IN ('Ativa', 'Finalizada', 'Cancelada')
    ),

    FOREIGN KEY (cpf_cliente) REFERENCES clientes(cpf),
    FOREIGN KEY (id_veiculo) REFERENCES veiculos(id_veiculo),

    CHECK (data_fim >= data_inicio)
);

INSERT INTO clientes (cpf, nome, telefone, email)
VALUES
('12345678900', 'João Silva', '41999991111', 'joao@email.com'),
('98765432100', 'Maria Souza', '41988882222', 'maria@email.com'),
('45678912300', 'Carlos Oliveira', '41977773333', 'carlos@email.com');

INSERT INTO veiculos (marca, modelo, ano, placa, valor_diaria, status_veiculo)
VALUES
('Fiat', 'Argo', 2022, 'ABC1D23', 120.00, 'Disponível'),
('Volkswagen', 'Gol', 2020, 'DEF4G56', 100.00, 'Disponível'),
('Chevrolet', 'Onix', 2023, 'HIJ7K89', 150.00, 'Manutenção');

INSERT INTO locacoes (
    cpf_cliente,
    id_veiculo,
    data_inicio,
    data_fim,
    valor_total,
    status_locacao
)
VALUES
('12345678900', 1, '2026-06-01', '2026-06-05', 480.00, 'Finalizada'),
('98765432100', 2, '2026-06-03', '2026-06-06', 300.00, 'Ativa'),
('45678912300', 1, '2026-06-10', '2026-06-12', 240.00, 'Ativa');

-- Consulta 1: clientes com CPF formatado.
SELECT
    SUBSTR(cpf, 1, 3) || '.' ||
    SUBSTR(cpf, 4, 3) || '.' ||
    SUBSTR(cpf, 7, 3) || '-' ||
    SUBSTR(cpf, 10, 2) AS cpf_formatado,
    nome,
    telefone,
    email
FROM clientes;

-- Consulta 2: veículos com valor da diária formatado.
SELECT
    id_veiculo,
    marca,
    modelo,
    ano,
    placa,
    'R$ ' || REPLACE(TO_CHAR(valor_diaria, 'FM999999990.00'), '.', ',') AS valor_diaria_formatado,
    status_veiculo
FROM veiculos;

-- Consulta 3: locações com datas e valor formatados.
SELECT
    id_locacao,
    SUBSTR(cpf_cliente, 1, 3) || '.' ||
    SUBSTR(cpf_cliente, 4, 3) || '.' ||
    SUBSTR(cpf_cliente, 7, 3) || '-' ||
    SUBSTR(cpf_cliente, 10, 2) AS cpf_cliente_formatado,
    id_veiculo,
    TO_CHAR(data_inicio, 'DD/MM/YYYY') AS data_inicio_formatada,
    TO_CHAR(data_fim, 'DD/MM/YYYY') AS data_fim_formatada,
    'R$ ' || REPLACE(TO_CHAR(valor_total, 'FM999999990.00'), '.', ',') AS valor_total_formatado,
    status_locacao
FROM locacoes;

-- Consulta 4: relatório completo de locações.
SELECT
    locacoes.id_locacao,
    SUBSTR(clientes.cpf, 1, 3) || '.' ||
    SUBSTR(clientes.cpf, 4, 3) || '.' ||
    SUBSTR(clientes.cpf, 7, 3) || '-' ||
    SUBSTR(clientes.cpf, 10, 2) AS cpf_formatado,
    clientes.nome,
    clientes.telefone,
    veiculos.marca,
    veiculos.modelo,
    veiculos.placa,
    TO_CHAR(locacoes.data_inicio, 'DD/MM/YYYY') AS data_inicio_formatada,
    TO_CHAR(locacoes.data_fim, 'DD/MM/YYYY') AS data_fim_formatada,
    'R$ ' || REPLACE(TO_CHAR(locacoes.valor_total, 'FM999999990.00'), '.', ',') AS valor_total_formatado,
    locacoes.status_locacao
FROM locacoes
INNER JOIN clientes
    ON locacoes.cpf_cliente = clientes.cpf
INNER JOIN veiculos
    ON locacoes.id_veiculo = veiculos.id_veiculo;
